-- 코드를 입력하세요
SELECT
    FO.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM
    FOOD_ORDER AS FO
JOIN
    FOOD_PRODUCT AS FP
ON
    FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE
    YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY
    FP.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC, FO.PRODUCT_ID ASC
