-- 코드를 작성해주세요

SELECT
    ID,
    CASE
        WHEN CHILD_COUNT IS NULL THEN 0
        ELSE CHILD_COUNT
    END AS CHILD_COUNT
FROM
    ECOLI_DATA
LEFT OUTER JOIN (
    SELECT
        PARENT_ID,
        COUNT(PARENT_ID) AS CHILD_COUNT
    FROM
        ECOLI_DATA
    GROUP BY
        PARENT_ID
) AS PARENT_INFO
ON ID = PARENT_INFO.PARENT_ID
