-- 코드를 작성해주세요
SELECT
    ID,
    FISH_NAME,
    MAX_LENGTH_INFO.LENGTH
FROM (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE
) AS MAX_LENGTH_INFO
JOIN
    FISH_INFO
ON
    MAX_LENGTH_INFO.LENGTH = FISH_INFO.LENGTH AND MAX_LENGTH_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
JOIN
    FISH_NAME_INFO
ON
    MAX_LENGTH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY
    ID
