-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * SALES_AMOUNT AS SALES
FROM PRODUCT
    JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
            FROM OFFLINE_SALE 
            GROUP BY PRODUCT_ID) AS T1 ON PRODUCT.PRODUCT_ID = T1.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC