-- 코드를 입력하세요
SELECT
    FOOD_PRODUCT.CATEGORY,
    MAX_PRICE_INFO.MAX_PRICE,
    PRODUCT_NAME
FROM
    FOOD_PRODUCT
JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
) AS MAX_PRICE_INFO
ON FOOD_PRODUCT.CATEGORY = MAX_PRICE_INFO.CATEGORY
AND FOOD_PRODUCT.PRICE = MAX_PRICE_INFO.MAX_PRICE
WHERE FOOD_PRODUCT.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE_INFO.MAX_PRICE DESC
