-- 코드를 입력하세요
SELECT T1.HOUR, IF(COUNT IS NULL, 0, COUNT)
FROM (SELECT RANK() OVER (ORDER BY ANIMAL_ID) - 1 AS HOUR
    FROM ANIMAL_OUTS) AS T1
    LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) T2 ON T1.HOUR = T2.HOUR
WHERE T1.HOUR < 24