-- 코드를 작성해주세요

SELECT ROUND(AVG(REAL_LENGTH), 2) AS AVERAGE_LENGTH
FROM (
    SELECT CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
            END REAL_LENGTH
    FROM FISH_INFO
) AS FISH_INFO
