-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES_AMOUNT * PRICE) TOTAL_SALES
FROM AUTHOR
    JOIN BOOK ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
    JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES_AMOUNT
            FROM BOOK_SALES
            WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
            GROUP BY BOOK_ID) AS BOOK_SALES ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC