-- 코드를 작성해주세요
SELECT
    DISTINCT ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM
    DEVELOPERS,
    SKILLCODES
WHERE
    (NAME = 'Python' or NAME = 'C#') AND (SKILL_CODE & CODE) > 0
ORDER BY
    ID
