-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
FROM
    USED_GOODS_FILE AS UGF
JOIN (
    SELECT
        BOARD_ID
    FROM
        USED_GOODS_BOARD
    ORDER BY
        VIEWS DESC
    LIMIT 1
) AS UGB
ON UGF.BOARD_ID = UGB.BOARD_ID
ORDER BY
    FILE_ID DESC
