-- 코드를 입력하세요
SELECT
    REST_INFO.FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM
    REST_INFO
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE
) AS MAX_FAVORITES_INFO
ON REST_INFO.FOOD_TYPE = MAX_FAVORITES_INFO.FOOD_TYPE
AND REST_INFO.FAVORITES = MAX_FAVORITES_INFO.MAX_FAVORITES
ORDER BY
    REST_INFO.FOOD_TYPE DESC
