SELECT CATEGORY, SUM(CNT) TOTAL_SALES
FROM BOOK
    JOIN (SELECT BOOK_ID, SUM(SALES) CNT
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
        GROUP BY BOOK_ID) AS BS ON BOOK.BOOK_ID = BS.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY